In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df['Spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [5]:
df.drop(['Category'],axis=1, inplace=True)

In [6]:
df.head()

Message  Spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Message'],df['Spam'], test_size=0.3)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [9]:
X_train_count = v.fit_transform(X_train.values)
X_test_count = v.transform(X_test)

In [10]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [11]:
y_pred = model.predict(X_test_count)

In [12]:
print( model.score(X_test_count, y_test))

0.9778708133971292


In [13]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1458
           1       0.95      0.87      0.91       214

    accuracy                           0.98      1672
   macro avg       0.97      0.93      0.95      1672
weighted avg       0.98      0.98      0.98      1672

[[1448   10]
 [  27  187]]


In [14]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

## Decision Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(X_train_count, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [16]:
y_pred= classifier.predict(X_test_count)  

In [17]:
print(classifier.score(X_test_count, y_test))

0.972488038277512


In [18]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1458
           1       0.92      0.86      0.89       214

    accuracy                           0.97      1672
   macro avg       0.95      0.92      0.94      1672
weighted avg       0.97      0.97      0.97      1672

[[1442   16]
 [  30  184]]


In [19]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
classifier.predict(emails_count)

array([0, 0], dtype=int64)

## KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier  
knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
knn.fit(X_train_count, y_train)  

KNeighborsClassifier()

In [21]:
y_pred=knn.predict(X_test_count)  

In [22]:
print(knn.score(X_test_count, y_test))

0.9174641148325359


In [23]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      1458
           1       1.00      0.36      0.52       214

    accuracy                           0.92      1672
   macro avg       0.96      0.68      0.74      1672
weighted avg       0.92      0.92      0.90      1672

[[1458    0]
 [ 138   76]]


In [24]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
knn.predict(emails_count)

array([0, 0], dtype=int64)

## SVM

In [25]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=0)  
svm.fit(X_train_count, y_train)  

SVC(kernel='linear', random_state=0)

In [26]:
y_pred=svm.predict(X_test_count) 

In [27]:
print(svm.score(X_test_count, y_test))

0.9814593301435407


In [28]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1458
           1       0.98      0.87      0.92       214

    accuracy                           0.98      1672
   macro avg       0.98      0.94      0.96      1672
weighted avg       0.98      0.98      0.98      1672

[[1454    4]
 [  27  187]]


In [29]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
svm.predict(emails_count)

array([0, 0], dtype=int64)